package vn.edu.tdtu.lhqc.budtrack.controllers.budget;

import android.content.Context;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import vn.edu.tdtu.lhqc.budtrack.database.budget.BudgetCategoryConverter;
import vn.edu.tdtu.lhqc.budtrack.database.budget.BudgetCategoryEntity;
import vn.edu.tdtu.lhqc.budtrack.database.budget.BudgetCategoryRepository;
import vn.edu.tdtu.lhqc.budtrack.models.BudgetCategory;

/**
 * BudgetCategoryManager manages budget-category relationships with persistence.
 * Uses Room database for storage.
 */
public final class BudgetCategoryManager {

    private BudgetCategoryManager() {
    }

    /**
     * Get all budget-category relationships.
     */
    public static List<BudgetCategory> getRelationships(Context context) {
        BudgetCategoryRepository repository = new BudgetCategoryRepository(context);
        List<BudgetCategoryEntity> entities = repository.getAllRelationships();
        return BudgetCategoryConverter.toModelList(entities);
    }

    /**
     * Get category IDs for a budget.
     */
    public static List<Long> getCategoryIdsForBudget(Context context, long budgetId) {
        BudgetCategoryRepository repository = new BudgetCategoryRepository(context);
        List<BudgetCategoryEntity> entities = repository.getRelationshipsByBudgetId(budgetId);
        List<Long> categoryIds = new ArrayList<>();
        for (BudgetCategoryEntity entity : entities) {
            categoryIds.add(entity.categoryId);
        }
        return categoryIds;
    }

    /**
     * Get budget IDs for a category.
     */
    public static List<Long> getBudgetIdsForCategory(Context context, long categoryId) {
        BudgetCategoryRepository repository = new BudgetCategoryRepository(context);
        List<BudgetCategoryEntity> entities = repository.getRelationshipsByCategoryId(categoryId);
        List<Long> budgetIds = new ArrayList<>();
        for (BudgetCategoryEntity entity : entities) {
            budgetIds.add(entity.budgetId);
        }
        return budgetIds;
    }

    /**
     * Add a budget-category relationship.
     */
    public static void addRelationship(Context context, long budgetId, long categoryId) {
        BudgetCategoryRepository repository = new BudgetCategoryRepository(context);
        
        // Check if relationship already exists
        if (repository.getRelationship(budgetId, categoryId) != null) {
            return; // Already exists
        }
        
        // Create new relationship (ID will be auto-generated by Room)
        BudgetCategoryEntity entity = new BudgetCategoryEntity(budgetId, categoryId);
        repository.insertRelationship(entity);
    }

    /**
     * Remove a budget-category relationship.
     */
    public static void removeRelationship(Context context, long budgetId, long categoryId) {
        BudgetCategoryRepository repository = new BudgetCategoryRepository(context);
        repository.deleteRelationship(budgetId, categoryId);
    }

    /**
     * Set categories for a budget (replaces all existing relationships for this budget).
     */
    public static void setCategoriesForBudget(Context context, long budgetId, List<Long> categoryIds) {
        BudgetCategoryRepository repository = new BudgetCategoryRepository(context);
        
        // Remove existing relationships for this budget
        repository.deleteAllForBudget(budgetId);
        
        // Add new relationships (IDs will be auto-generated by Room)
        for (Long categoryId : categoryIds) {
            BudgetCategoryEntity entity = new BudgetCategoryEntity(budgetId, categoryId);
            repository.insertRelationship(entity);
        }
    }

    /**
     * Remove all relationships for a budget (when budget is deleted).
     */
    public static void removeAllForBudget(Context context, long budgetId) {
        BudgetCategoryRepository repository = new BudgetCategoryRepository(context);
        repository.deleteAllForBudget(budgetId);
    }

    /**
     * Get category IDs that are already used in other budgets (excluding the specified budget).
     * This is used to prevent selecting categories that are already assigned to other budgets.
     * 
     * @param context The context
     * @param excludeBudgetId The budget ID to exclude from the check (e.g., current budget being edited)
     * @return Set of category IDs that are already used in other budgets
     */
    public static Set<Long> getCategoriesUsedByOtherBudgets(Context context, long excludeBudgetId) {
        BudgetCategoryRepository repository = new BudgetCategoryRepository(context);
        return repository.getCategoryIdsUsedByOtherBudgets(excludeBudgetId);
    }
}

