package vn.edu.tdtu.lhqc.budtrack.controllers.budget;

import android.content.Context;

import java.util.List;

import vn.edu.tdtu.lhqc.budtrack.database.budget.BudgetConverter;
import vn.edu.tdtu.lhqc.budtrack.database.budget.BudgetEntity;
import vn.edu.tdtu.lhqc.budtrack.database.budget.BudgetRepository;
import vn.edu.tdtu.lhqc.budtrack.models.Budget;

/**
 * BudgetManager manages budget data with persistence.
 * Uses Room database for storage.
 */
public final class BudgetManager {

    private BudgetManager() {
    }

    /**
     * Get all budgets.
     */
    public static List<Budget> getBudgets(Context context) {
        BudgetRepository repository = new BudgetRepository(context);
        List<BudgetEntity> entities = repository.getAllBudgets();
        return BudgetConverter.toModelList(entities);
    }

    /**
     * Get a budget by ID.
     */
    public static Budget getBudgetById(Context context, long id) {
        BudgetRepository repository = new BudgetRepository(context);
        BudgetEntity entity = repository.getBudgetById(id);
        return BudgetConverter.toModel(entity);
    }

    /**
     * Add a new budget.
     * The budget ID will be auto-generated by Room. The returned ID is set back to the budget object.
     */
    public static void addBudget(Context context, Budget budget) {
        BudgetRepository repository = new BudgetRepository(context);
        BudgetEntity entity = BudgetConverter.toEntity(budget);
        
        // Room will auto-generate the ID since BudgetEntity.id has @PrimaryKey(autoGenerate = true)
        // Set id to 0 to let Room generate it
        entity.id = 0;
        
        long generatedId = repository.insertBudget(entity);
        // Update the budget model with the generated ID
        budget.setId(generatedId);
    }

    /**
     * Update a budget.
     */
    public static void updateBudget(Context context, Budget budget) {
        BudgetRepository repository = new BudgetRepository(context);
        BudgetEntity entity = BudgetConverter.toEntity(budget);
        repository.updateBudget(entity);
    }

    /**
     * Remove a budget by ID.
     */
    public static void removeBudget(Context context, long budgetId) {
        BudgetRepository repository = new BudgetRepository(context);
        repository.deleteBudgetById(budgetId);
    }
}

